Repository GEOS-ESM/GOCART, pull requests merged in 2022-09, with the labels that each got.

#187 Fixes #184. Remove unneeded GFE find_package calls
  .circleci/config.yml
  CHANGELOG.md
  CMakeLists.txt
  ESMF/UFS/Aerosol_Internal_Mod.F90
Labels: 0 diff

#189 Feature/vbuchard/extinction export
  CHANGELOG.md
  ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_GridCompMod.F90
  ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_StateSpecs.rc
  ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_GridCompMod.F90
  ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_StateSpecs.rc
  ESMF/GOCART2G_GridComp/GOCART2G_GridCompMod.F90
  ESMF/GOCART2G_GridComp/GOCART2G_StateSpecs.rc
  ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_GridCompMod.F90
  ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_StateSpecs.rc
  ESMF/GOCART2G_GridComp/SS2G_GridComp/SS2G_GridCompMod.F90
  ESMF/GOCART2G_GridComp/SS2G_GridComp/SS2G_StateSpecs.rc
  ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_GridCompMod.F90
  ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_StateSpecs.rc
  Process_Library/GOCART2G_Process.F90
Labels: 0 diff, enhancement

#188 Update CI BCs version to fix GEOSgcm run
  .circleci/config.yml
  CHANGELOG.md
Labels: 0 diff trivial
