Repository GEOS-ESM/GOCART, pull requests merged in 2024-09, with the labels that each got.

#264 Feature/pcolarco/#263/su2g_gridcompmod logic
  .github/workflows/validate_yaml_files.yml
  CHANGELOG.md
  ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_GridCompMod.F90
Labels: 0 diff structural, bugfix

#266 Feature/pcolarco/carbon chem loss upd
  CHANGELOG.md
  ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_GridCompMod.F90
  ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_StateSpecs.rc
  ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_instance_CA.bc.rc
  ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_instance_CA.br.rc
  ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_instance_CA.oc.rc
  Process_Library/GOCART2G_Process.F90
Labels: Non 0-diff, enhancement

#288 Set `k` in `SUvolcanicEmissions` to be integer
  CHANGELOG.md
  Process_Library/GOCART2G_Process.F90
Labels: 0 diff, bugfix

#290 Fixes #289 Correct CHANGELOG.md
  CHANGELOG.md
Labels: 0 diff trivial, bug
