Repository GEOS-ESM/GOCART, pull requests merged in 2024-08, with the labels that each got.

#251 feature/acollow/#233_aodlongnames
  CHANGELOG.md
  ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_StateSpecs.rc
  ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_StateSpecs.rc
  ESMF/GOCART2G_GridComp/GOCART2G_StateSpecs.rc
  ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_StateSpecs.rc
  ESMF/GOCART2G_GridComp/SS2G_GridComp/SS2G_StateSpecs.rc
  ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_StateSpecs.rc
Labels: 0 diff

#257 corrected reading 'rhod'
  CHANGELOG.md
  Process_Library/GOCART2G_MieMod.F90
  Process_Library/MieQuery.H
Labels: Non 0-diff, bugfix

#259 Feature/mfmehari/krok obio
  CHANGELOG.md
  ESMF/Shared/Chem_AeroGeneric.F90
Labels: 0 diff

#269 Removed all *ExtData.rc from GOCART/
  CHANGELOG.md
  ESMF/GOCART2G_GridComp/CA2G_GridComp/AMIP.20C/CA2G_GridComp_ExtData.rc
  ESMF/GOCART2G_GridComp/DU2G_GridComp/AMIP.20C/DU2G_GridComp_ExtData.rc
  ESMF/GOCART2G_GridComp/DU2G_GridComp/AMIP/DU2G_GridComp_ExtData.rc
  ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_GridComp_ExtData.rc
  ESMF/GOCART2G_GridComp/NI2G_GridComp/AMIP.20C/NI2G_GridComp_ExtData.rc
  ESMF/GOCART2G_GridComp/SS2G_GridComp/AMIP.20C/SS2G_GridComp_ExtData.rc
  ESMF/GOCART2G_GridComp/SS2G_GridComp/AMIP/SS2G_GridComp_ExtData.rc
  ESMF/GOCART2G_GridComp/SS2G_GridComp/SS2G_GridComp_ExtData.rc
  ESMF/GOCART2G_GridComp/SU2G_GridComp/AMIP.20C/SU2G_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/CFC_GridComp/AMIP.20C/CFC_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/CFC_GridComp/AMIP/CFC_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/CFC_GridComp/CFC_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/CH4_GridComp/AMIP.20C/CH4_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/CH4_GridComp/AMIP/CH4_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/CH4_GridComp/CH4_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/CO2_GridComp/AMIP.20C/CO2_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/CO2_GridComp/AMIP/CO2_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/CO2_GridComp/CO2_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/CO_GridComp/AMIP.20C/CO_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/CO_GridComp/AMIP/CO_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/CO_GridComp/CO_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/O3_GridComp/AMIP.20C/O3_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/O3_GridComp/AMIP/O3_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/O3_GridComp/O3_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/Rn_GridComp/AMIP.20C/Rn_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/Rn_GridComp/AMIP/Rn_GridComp_ExtData.rc
  ESMF/GOCART_GridComp/Rn_GridComp/Rn_GridComp_ExtData.rc
Labels: 0 diff

#270 Update components to match GEOSgcm v11.6.0
  CHANGELOG.md
  components.yaml
Labels: 0 diff

#273 Fix CMake circular dependencies for external use
  CHANGELOG.md
  CMakeLists.txt
  ESMF/Shared/CMakeLists.txt
Labels: 0 diff

#283 CEDS Filepath Update for G2G Develop
  CHANGELOG.md
  ESMF/GOCART2G_GridComp/CA2G_GridComp/AMIP/CA2G_GridComp_ExtData.yaml
  ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_GridComp_ExtData.yaml
  ESMF/GOCART2G_GridComp/NI2G_GridComp/AMIP/NI2G_GridComp_ExtData.yaml
  ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_GridComp_ExtData.yaml
  ESMF/GOCART2G_GridComp/SU2G_GridComp/AMIP/SU2G_GridComp_ExtData.yaml
  ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_GridComp_ExtData.yaml
Labels: Non 0-diff, bugfix

#262 Replay import patch for ozone
  CHANGELOG.md
  ESMF/GOCART_GridComp/O3_GridComp/O3_GridCompMod.F90
Labels: Non 0-diff

#265 changes to allow for radii from the optics files to be used for settling
  CHANGELOG.md
  ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_GridCompMod.F90
  ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_instance_CA.bc.rc
  ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_instance_CA.br.rc
  ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_instance_CA.oc.rc
  ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_GridCompMod.F90
  ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_instance_DU.rc
  ESMF/GOCART2G_GridComp/GA_Environment/GA_EnvironmentMod.F90
  ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_GridCompMod.F90
  ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_instance_NI.rc
  ESMF/GOCART2G_GridComp/SS2G_GridComp/SS2G_GridCompMod.F90
  ESMF/GOCART2G_GridComp/SS2G_GridComp/SS2G_instance_SS.rc
  ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_GridCompMod.F90
  ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_instance_SU.rc
  Process_Library/GOCART2G_Process.F90
  Process_Library/MieQuery.H
Labels: Non 0-diff

#284 Fix UFS diagnostic PM calculations to properly identify carbonaceous aerosols
  CHANGELOG.md
  ESMF/UFS/Aerosol_Diag_Mod.F90
Labels: 0 diff trivial

#261 prc: updates to include separate explosive and degassing volcanic emissions for SO2
  CHANGELOG.md
  ESMF/GOCART2G_GridComp/SU2G_GridComp/AMIP.20C/SU2G_instance_SU.rc
  ESMF/GOCART2G_GridComp/SU2G_GridComp/AMIP/SU2G_instance_SU.rc
  ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_GridCompMod.F90
  ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_instance_SU.rc
  Process_Library/GOCART2G_Process.F90
Labels: 0 diff

#260 prc: added an export to GOCART2G to connect SU sulfate production to …
  CHANGELOG.md
  ESMF/GOCART2G_GridComp/GOCART2G_GridCompMod.F90
Labels: 0 diff trivial

#286 Update ESMF CMake target to ESMF::ESMF
  CHANGELOG.md
  ESMF/Aerosol_GridComp/CMakeLists.txt
  ESMF/Apps/CMakeLists.txt
  ESMF/GOCART2G_GridComp/CA2G_GridComp/CMakeLists.txt
  ESMF/GOCART2G_GridComp/CMakeLists.txt
  ESMF/GOCART2G_GridComp/DU2G_GridComp/CMakeLists.txt
  ESMF/GOCART2G_GridComp/GA_Environment/CMakeLists.txt
  ESMF/GOCART2G_GridComp/NI2G_GridComp/CMakeLists.txt
  ESMF/GOCART2G_GridComp/SS2G_GridComp/CMakeLists.txt
  ESMF/GOCART2G_GridComp/SU2G_GridComp/CMakeLists.txt
  ESMF/GOCART_GridComp/CFC_GridComp/CMakeLists.txt
  ESMF/GOCART_GridComp/CMakeLists.txt
  ESMF/GOCART_GridComp/CO2_GridComp/CMakeLists.txt
  ESMF/GOCART_GridComp/CO_GridComp/CMakeLists.txt
  ESMF/GOCART_GridComp/Rn_GridComp/CMakeLists.txt
  ESMF/Shared/CMakeLists.txt
  ESMF/UFS/CMakeLists.txt
  Process_Library/CMakeLists.txt
Labels: 0 diff structural

#287 Fix issue between UFS build and standalone CMake
  CHANGELOG.md
  CMakeLists.txt
Labels: 0 diff, bugfix
